server:
  port: 8080
  error:
    path: /error
  servlet:
    context-path: /alsace-service

spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
    url: jdbc:mysql://localhost:3306/alsace?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

